pericias = ['Acrobacia(Dex)',
            'Atletismo(For)',
            'Atuação(Car)',
            'Blefar(Car)',
            'Enganação(Car)',
            'Eguer peso(For)',
            'Esquiva(Des)',
            'Furtividade(Des)',
            'Historia(Int)',
            'Indentificar magia(Int)',
            'Intuição(Sab)',
            'Intimidação(Car)',
            'Ladinagem(Des)',
            'Lidinagem(Des)',
            'Lidar com animais(Sab)',
            'Medicina(Sab)',
            'Natureza(Int)',
            'Obter informação(Car)',
            'Percepção(Sab)',
            'Religião(Int)']

tendencias = [
    'Leal e bom',
    'Neutro e bom',
    'Caótico e bom',
    'Leal e neutro',
    'Neutro',
    'Caótico neutro',
    'Leal e mau',
    'Neutro e mau',
    'Caótico e mau']
